package resources;

import java.util.ListResourceBundle;

public class Resource_cat_CAT extends ListResourceBundle {



    private static final Object[][] CONTENTS = {
        {"Eneter host address", "Introduïu l ' adreça de la màquina"},
        {"Eneter host port", "Introduïu el port amfitrió"},
        {"connect", "connecta"},
        {"Error to connect to server", "Error en connectar al servidor"},
        {"Eneter your username", "Introduïu el vostre nom d'usuari"},
        {"Eneter your password", "Introduïu la vostra contrasenya"},
        {"Log In", "Inicia Sessió"},
        {"Sign Up", "Inscriure'S"},
        {"Login or password is incorrect", "Login o contrasenya són incorrectes"},
        {"This username is already used", "Aquest nom d 'usuari ja s' usa"},
        {"YES", "SÍ"},
        {"NO", "NO"},
        {"Do you want exit?", "Vols sortir?"},
        {"Sort", "Sort"},
        {"Filter", "Filtre"},
        {"id", "id"},
        {"name", "nom"},
        {"x", "x"},
        {"y", "y"},
        {"creation Time", "temps de creació"},
        {"health", "salut"},
        {"heartCount", "recompte cor"},
        {"loyal", "lleial"},
        {"category", "categoria"},
        {"chapter", "capítol"},
        {"parentLegion", "legió mare"},
        {"marinesCount", "comptador marines"},
        {"world", "món"},
        {"ownername", "nom del propietari"},
        {"increase", "augmenta"},
        {"decrease", "disminueix"},
        {"equals", "iguals"},
        {"greater", "gran"},
        {"lower", "baixa"},
        {"Table View", "Vista De Taula"},
        {"Visual View", "Vista Visual"},
        {"Command Panel", "Panell D ' Ordres"},
        {"sort", "sort"},
        {"input", "entrada"},
        {"Enter value of field: ", "Introduïu el valor del camp: "},
        {"filter", "filtre"},
        {"Choose command", "Escolliu ordre"},
        {"null", "null"},
        {"true", "cert"},
        {"false", "fals"},
        {"push", "push"},
        {"help", "ajuda"},
        {"info", "informació"},
        {"show", "mostra"},
        {"update", "actualizacao"},
        {"remove_by_id", "elimina_per_id"},
        {"clear", "desmarcar"},
        {"execute_script", "executa_l'script"},
        {"exit", "sortida"},
        {"remove_greater", "elimina_major"},
        {"remove_lower", "elimina_inferior"},
        {"group_counting_by_name", "grup_comptant_per_nom"},
        {"add_if_min", "afegeix_si_mín"},
        {"print_descending", "imprimeix descendent"},
        {"count_by_loyal", "conde de loyal"},
        {"add", "afegeix"},
        {"aggressor", "agressor"},
        {"tactical", "tactical"},
        {"inceptor", "inceptor"},
        {"helix", "helix"},
        {"Field", "Camp"},
        {"Value", "Valor"},
        {"Requirement", "Requisit"},
        {"Not empty", "No buit"},
        {"Any double", "Qualsevol doble"},
        {"Not null", "No nul"},
        {"Integer, >0", "Enter, >0"},
        {"Integer, 0<x<4", "Enter, 0<x<4"},
        {"May be null", "Pot ser nul"},
        {"Any string", "Qualsevol cadena"},
        {"Integer, 0<x<1001", "Enter, 0<x<1001"},
        {"submit", "sant feliu de guíxols"},
        {"Invalid arguments", "Arguments no vàlids"},
        {"reload", "recarrega"},
        {"NumberFormatException", "Excepció Del Format Del Número"},
        {"It is not your spaceMarine", "No és la teva nau espacial"},
        {"OK", "BÉ"},
        {"Русский", "Русский"},
        {"Português", "Português"},
        {"Español", "Español"},
        {"Català", "Català"},
        {"", ""},
        {"SpaceMarine has been added.", "Воин добалвен"},
        {"SpaceMarine already exists.", "Воин уже существует"},
        {"Element is bigger than minimum.", "Элемент больше чем минимальный"},
        {"Database broke down.", "База данных сломалась"},
        {"SpaceMarine has been removed.", "Воин списан со счетов"},
        {"Uknown Id or insufficient access rights.", "Неизвестный Id или это не ваш воин"},
        {"All items have been successfully deleted.", "Все элементы удалены"},
        {"No element has been deleted.", "Никто не удален"},
        {"Marine has been successfully updated.", "Воин изменен"},
        {"Id is not correct or insufficient access rights.", "Неверный Id или это не ваш воин"},
        {"Connection lost", "Connexió perduda"}
    };



    @Override
    protected Object[][] getContents() {
        return CONTENTS;
    }
}
