package resources;

import java.util.ListResourceBundle;

public class Resource_es_PR extends ListResourceBundle {



    private static final Object[][] CONTENTS = {
        {"Eneter host address", "Introduzca la dirección de host"},
        {"Eneter host port", "Introduzca el puerto de host"},
        {"connect", "conectar"},
        {"Error to connect to server", "Error al conectarse al servidor"},
        {"Eneter your username", "Ingrese su nombre de usuario"},
        {"Eneter your password", "Ingrese su contraseña"},
        {"Log In", "Iniciar Sesión"},
        {"Sign Up", "Inscribir"},
        {"Login or password is incorrect", "El nombre de usuario o la contraseña son incorrectos"},
        {"This username is already used", "Este nombre de usuario ya está en uso"},
        {"YES", "Sí"},
        {"NO", "NO"},
        {"Do you want exit?", "¿Quieres salir?"},
        {"Sort", "Tipo"},
        {"Filter", "Filtro"},
        {"id", "id"},
        {"name", "nombre"},
        {"x", "x"},
        {"y", "y"},
        {"creation Time", "tiempo de Creación"},
        {"health", "salud"},
        {"heartCount", "recuento de Corazones"},
        {"loyal", "leal"},
        {"category", "categoría"},
        {"chapter", "capitulo"},
        {"parentLegion", "legión de Padres"},
        {"marinesCount", "recuento de marines"},
        {"world", "mundo"},
        {"ownername", "nombre del propietario"},
        {"increase", "aumentar"},
        {"decrease", "diminuir"},
        {"equals", "igual"},
        {"greater", "greater"},
        {"lower", "inferior"},
        {"Table View", "Vista de Tabla"},
        {"Visual View", "Vista Visual"},
        {"Command Panel", "Panel de Control"},
        {"sort", "tipo"},
        {"input", "entrada"},
        {"Enter value of field", "Introduzca el valor del campo"},
        {"filter", "filtro"},
        {"Choose command", "Elegir comando"},
        {"null", "nulo"},
        {"true", "verdadero"},
        {"false", "falso"},
        {"push", "empujar"},
        {"help", "ayudar"},
        {"info", "info"},
        {"show", "demostrar"},
        {"update", "actualizar"},
        {"remove_by_id", "eliminar_por_id"},
        {"clear", "claro"},
        {"execute_script", "ejecutar_script"},
        {"exit", "salida"},
        {"remove_greater", "quitar_mayor"},
        {"remove_lower", "quitar_inferior"},
        {"group_counting_by_name", "conteo_de_grupos_por_nombre"},
        {"add_if_min", "añadir_if_min"},
        {"print_descending", "impresión_descendente"},
        {"count_by_loyal", "contar_por_leal"},
        {"add", "añadir"},
        {"aggressor", "agresor"},
        {"tactical", "táctico"},
        {"inceptor", "inceptor"},
        {"helix", "hélice"},
        {"Field", "Campo"},
        {"Value", "Valor"},
        {"Requirement", "Requisito"},
        {"Not empty", "No vacío"},
        {"Any double", "Cualquier doble"},
        {"Not null", "No null"},
        {"Integer, >0", "Entero, >0"},
        {"Integer, 0<x<4", "Entero, 0<x<4"},
        {"May be null", "Puede ser null"},
        {"Any string", "Cualquier cadena"},
        {"Integer, 0<x<1001", "Entero, 0<x<1001"},
        {"submit", "presentar"},
        {"Invalid arguments", "Argumentos no válidos"},
        {"reload", "cargar"},
        {"NumberFormatException", "Excepción de Formato de Número"},
        {"It is not your spaceMarine", "No es su spaceMarine"},
        {"OK", "OK"},
        {"Русский", "Русский"},
        {"Português", "Português"},
        {"Español", "Español"},
        {"Català", "Català"},
        {"", ""},
        {"SpaceMarine has been added.", "Воин добалвен"},
        {"SpaceMarine already exists.", "Воин уже существует"},
        {"Element is bigger than minimum.", "Элемент больше чем минимальный"},
        {"Database broke down.", "База данных сломалась"},
        {"SpaceMarine has been removed.", "Воин списан со счетов"},
        {"Uknown Id or insufficient access rights.", "Неизвестный Id или это не ваш воин"},
        {"All items have been successfully deleted.", "Все элементы удалены"},
        {"No element has been deleted.", "Никто не удален"},
        {"Marine has been successfully updated.", "Воин изменен"},
        {"Id is not correct or insufficient access rights.", "Неверный Id или это не ваш воин"},
        {"Connection lost", "Se ha perdido la conexión"},
        {"Number format is wrong", "Неверный формат"},
        {"Error to connect to server", "Ошибка подключения к серверу"}
        };


    @Override
    protected Object[][] getContents() {
        return CONTENTS;
    }
}
