package com.ut.resources;

// package zula.resources;

import java.util.ListResourceBundle;

public class Resource_pt_PT extends ListResourceBundle {



    private static final Object[][] CONTENTS = {
        {"Eneter host address", "Digite o endereço do host"},
        {"Eneter host port", "Digite a porta do host"},
        {"connect", "conectar"},
        {"Error to connect to server", "Erro para conectar ao servidor"},
        {"Eneter your username", "Digite seu nome de usuário"},
        {"Eneter your password", "Eneter your password"},
        {"Log In", "conectar"},
        {"Sign Up", "inscrever"},
        {"Login or password is incorrect", "Login ou senha está incorreto"},
        {"This username is already used", "Este nome de usuário já é usado"},
        {"yes", "SIM"},
        {"no", "Não"},
        {"Do you want to exit?", "Queres sair?"},
        {"id", "ID"},
        {"name", "nome"},
        {"x", "x"},
        {"y", "y"},
        {"creation Time", "criacao"},
        {"health", "saude"},
        {"heartCount", "contagem do coração"},
        {"loyal", "leal"},
        {"category", "categoria"},
        {"chapter", "capitulo"},
        {"parentLegion", "Legião dos pais"},
        {"marinesCount", "marines Count"},
        {"world", "mundo"},
        {"ownername", "nome do proprietário"},
        {"increase", "aumentar"},
        {"decrease", "diminuir"},
        {"equals", "igual"},
        {"greater", "maior"},
        {"lower", "inferior"},
        {"Table View", "Tabela"},
        {"Visual View", "Vista Visual"},
        {"Command Panel", "Painel De Comando"},
        {"sort", "tipo"},
        {"input", "entrada"},
        {"Enter value of field", "Introduza o valor do campo"},
        {"filter", "filtro"},
        {"Choose command", "Escolha o comando"},
        {"null", "nulo"},
        {"true", "verdadeiro"},
        {"false", "falso"},
        {"push", "empurrar"},
        {"help", "ajudar"},
        {"info", "informacao"},
        {"show", "mostrar"},
        {"update", "actualizacao"},
        {"remove_by_id", "remover_por_id"},
        {"clear", "desmarcar"},
        {"execute_script", "executar_script"},
        {"exit", "sair"},
        {"remove_greater", "remover_maior"},
        {"remove_lower", "remover_inferior"},
        {"group_counting_by_name", "contagem_de_grupos_por_nome"},
        {"add_if_min", "adicionar_se_min"},
        {"print_descending", "imprimir_descendente"},
        {"count_by_loyal", "contagem_por_leal"},
        {"add", "adicionar"},
        {"aggressor", "agressor"},
        {"tactical", "tactico"},
        {"inceptor", "inceptor"},
        {"helix", "helice"},
        {"field", "Campo"},
        {"value", "Valor"},
        {"Requirement", "Requisito"},
        {"Not empty", "Não vazio"},
        {"Any double", "Qualquer duplo"},
        {"Not null", "Não nulo"},
        {"Integer, >0", "Inteiro, >0"},
        {"Integer, 0<x<4", "Inteiro, 0<x<4"},
        {"May be null", "Pode ser nulo"},
        {"Any string", "Qualquer string"},
        {"Integer, 0<x<1001", "Inteiro, 0<x<1001"},
        {"submit", "enviar"},
        {"Invalid arguments", "Argumentos inválidos"},
        {"reload", "recarregar"},
        {"NumberFormatException", "Exceção De Formato De Número"},
        {"It is not your spaceMarine", "Não é o seu spaceMarine"},
        {"OK", "BEM"},
        {"Русский", "Русский"},
        {"Português", "Português"},
        {"Español", "Español"},
        {"Català", "Català"},
        {"", ""},
        {"SpaceMarine has been added.", "Space Marine foi adicionado."},
        {"SpaceMarine already exists.", "O espaço marinho já existe."},
        {"Element is bigger than minimum.", "O elemento é maior que o mínimo."},
        {"Database broke down.", "Banco de dados quebrou."},
        {"SpaceMarine has been removed.", "O Space Marine foi removido."},
        {"Uknown Id or insufficient access rights.", "Id desconhecido ou direitos de acesso insuficientes."},
        {"All items have been successfully deleted.", "Todos os itens foram excluídos com sucesso."},
        {"No element has been deleted.", "Nenhum elemento foi excluído."},
        {"Marine has been successfully updated.", "Marine foi atualizado com sucesso."},
        {"Id is not correct or insufficient access rights or dublicated elements.", "Id não é direitos de acesso corretos ou insuficientes"},
        {"Connection lost", "Conexão perdida"},
        {"Number format is wrong", "O formato do número está errado"},
        {"Error to connect to server", "Erro para conectar ao servidor"},
        {"IOException", "IOException"},
        {"Data is corrupted.", "Os dados estão corrompidos."}
    };

    @Override
    protected Object[][] getContents() {
        return CONTENTS;
    }
}
