package com.ut.resources;

import java.util.ListResourceBundle;

public class Resource_es_PR extends ListResourceBundle {



    private static final Object[][] CONTENTS = {
        {"Eneter host address", "Introduzca la dirección de host"},
        {"Eneter host port", "Introduzca el puerto de host"},
        {"connect", "conectar"},
        {"Error to connect to server", "Error al conectarse al servidor"},
        {"Eneter your username", "Ingrese su nombre de usuario"},
        {"Eneter your password", "Ingrese su contraseña"},
        {"Log In", "Iniciar Sesión"},
        {"Sign Up", "Inscribir"},
        {"Login or password is incorrect", "El nombre de usuario o la contraseña son incorrectos"},
        {"This username is already used", "Este nombre de usuario ya está en uso"},
        {"yes", "Sí"},
        {"no", "NO"},
        {"Do you want to exit?", "¿Quieres salir?"},
        {"id", "id"},
        {"name", "nombre"},
        {"x", "x"},
        {"y", "y"},
        {"creation Time", "tiempo de Creación"},
        {"health", "salud"},
        {"heartCount", "recuento de Corazones"},
        {"loyal", "leal"},
        {"category", "categoría"},
        {"chapter", "capitulo"},
        {"parentLegion", "legión de Padres"},
        {"marinesCount", "recuento de marines"},
        {"world", "mundo"},
        {"ownername", "nombre del propietario"},
        {"increase", "aumentar"},
        {"decrease", "diminuir"},
        {"equals", "igual"},
        {"greater", "greater"},
        {"lower", "inferior"},
        {"Table View", "Vista de Tabla"},
        {"Visual View", "Vista Visual"},
        {"Command Panel", "Panel de Control"},
        {"sort", "tipo"},
        {"input", "entrada"},
        {"Enter value of field", "Introduzca el valor del campo"},
        {"filter", "filtro"},
        {"Choose command", "Elegir comando"},
        {"null", "nulo"},
        {"true", "verdadero"},
        {"false", "falso"},
        {"push", "empujar"},
        {"help", "ayudar"},
        {"info", "info"},
        {"show", "demostrar"},
        {"update", "actualizar"},
        {"remove_by_id", "eliminar_por_id"},
        {"clear", "claro"},
        {"execute_script", "ejecutar_script"},
        {"exit", "salida"},
        {"remove_greater", "quitar_mayor"},
        {"remove_lower", "quitar_inferior"},
        {"group_counting_by_name", "conteo_de_grupos_por_nombre"},
        {"add_if_min", "añadir_if_min"},
        {"print_descending", "impresión_descendente"},
        {"count_by_loyal", "contar_por_leal"},
        {"add", "añadir"},
        {"aggressor", "agresor"},
        {"tactical", "táctico"},
        {"inceptor", "inceptor"},
        {"helix", "hélice"},
        {"field", "Campo"},
        {"value", "Valor"},
        {"Requirement", "Requisito"},
        {"Not empty", "No vacío"},
        {"Any double", "Cualquier doble"},
        {"Not null", "No null"},
        {"Integer, >0", "Entero, >0"},
        {"Integer, 0<x<4", "Entero, 0<x<4"},
        {"May be null", "Puede ser null"},
        {"Any string", "Cualquier cadena"},
        {"Integer, 0<x<1001", "Entero, 0<x<1001"},
        {"submit", "presentar"},
        {"Invalid arguments", "Argumentos no válidos"},
        {"reload", "cargar"},
        {"NumberFormatException", "Excepción de Formato de Número"},
        {"It is not your spaceMarine", "No es su spaceMarine"},
        {"OK", "OK"},
        {"Русский", "Русский"},
        {"Português", "Português"},
        {"Español", "Español"},
        {"Català", "Català"},
        {"", ""},
        {"SpaceMarine has been added.", "Se ha añadido el marine espacial."},
        {"SpaceMarine already exists.", "Los marines espaciales ya existen."},
        {"Element is bigger than minimum.", "El elemento es mayor que el mínimo."},
        {"Database broke down.", "La base de datos se rompió."},
        {"SpaceMarine has been removed.", "El marine espacial ha sido eliminado."},
        {"Uknown Id or insufficient access rights.", "Id desconocido o derechos de acceso insuficientes."},
        {"All items have been successfully deleted.", "Todos los elementos se han eliminado correctamente."},
        {"No element has been deleted.", "No se ha eliminado ningún elemento."},
        {"Marine has been successfully updated.", "Marine se ha actualizado correctamente."},
        {"Id is not correct or insufficient access rights or dublicated elements.", "La identificación no es correcta o los derechos de acceso son insuficientes."},
        {"Connection lost", "Se ha perdido la conexión"},
        {"Number format is wrong", "El formato de número es incorrecto"},
        {"Error to connect to server", "Error al conectarse al servidor"},
        {"IOException", "IOException"},
        {"Data is corrupted.", "los datos están dañados."}
        };


    @Override
    protected Object[][] getContents() {
        return CONTENTS;
    }
}
