package com.ut.resources;


import java.util.ListResourceBundle;

public class Resource_ru_RU extends ListResourceBundle {


    private static final Object[][] CONTENTS = {
            {"Eneter host address", "Введите адрес сервера"},
            {"Eneter host port", "Введите порт сервера"},
            {"connect", "подключиться"},
            {"Error to connect to server", "Ошибка подключения к серверу"},
            {"Eneter your username", "Введите логин"},
            {"Eneter your password", "Введите пароль"},
            {"Log In", "войти"},
            {"Sign Up", "зарегистрироваться"},
            {"Login or password is incorrect", "Логин или пароль неверен"},
            {"This username is already used", "Данный логин занят"},
            {"yes", "Да"},
            {"no", "Нет"},
            {"Do you want to exit?", "Вы хотите выйти?"},
            {"id", "id"},
            {"name", "имя"},
            {"x", "х"},
            {"y", "у"},
            {"creation Time", "Время создания"},
            {"health", "здоровье"},
            {"heartCount", "количество сердец"},
            {"loyal", "верность"},
            {"category", "категория"},
            {"chapter", "чаптер"},
            {"parentLegion", "легион"},
            {"marinesCount", "количество воинов"},
            {"world", "мир"},
            {"ownername", "владелец"},
            {"increase", "по возрастанию"},
            {"decrease", "по убыванию"},
            {"equals", "равен"},
            {"greater", "больше"},
            {"lower", "меньше"},
            {"Table View", "Таблица"},
            {"Visual View", "Визуализация"},
            {"Command Panel", "Команды"},
            {"sort", "сортировать"},
            {"input", "ввести значение"},
            {"Enter value of field", "Введите значение поля"},
            {"filter", "фильтровать"},
            {"Choose command", "Выберите команду"},
            {"null", "неизвостно"},
            {"true", "верно"},
            {"false", "неверно"},
            {"push", "отправить"},
            {"help", "Помощь"},
            {"info", "Информация"},
            {"show", "Показать коллекцию"},
            {"update", "Обновить воина"},
            {"remove_by_id", "Удалить воина"},
            {"clear", "Удалить всех"},
            {"execute_script", "Выполнить скрипт"},
            {"exit", "Завершение работы"},
            {"remove_greater", "Удалить больших чем"},
            {"remove_lower", "Удалить меньших чем"},
            {"group_counting_by_name", "Группировать по имени"},
            {"add_if_min", "Добавить воина, если он меньше всех"},
            {"print_descending", "Напечатать по убыванию"},
            {"count_by_loyal", "Посчитать по верности"},
            {"add", "Добавить воина"},
            {"aggressor", "агрессор"},
            {"tactical", "тактик"},
            {"inceptor", "инициатор"},
            {"helix", "медик"},
            {"field", "Поле"},
            {"value", "Значение"},
            {"Requirement", "Требования"},
            {"Not empty", "Не пустое"},
            {"Any double", "Любое double"},
            {"Not null", "Не нуль"},
            {"Integer, >0", "Integer, >0"},
            {"Integer, 0<x<4", "Integer, 0<x<4"},
            {"May be null", "Может быть нулем"},
            {"Any string", "Любая строка"},
            {"Integer, 0<x<1001", "Integer, 0<x<1001"},
            {"submit", "отправить"},
            {"Invalid arguments", "Неверные аргументы"},
            {"reload", "обновить"},
            {"NumberFormatException", "Неверное значение"},
            {"It is not your spaceMarine", "Это не ваш воин"},
            {"OK", "Ок"},
            {"Russian", " Русский"},
            {"Portuguese", "Português"},
            {"Spanish", "Español"},
            {"Catalan", "Català"},
            {"Number format is wrong", "Неверный формат числа"},
            {"Русский", "Русский"},
            {"Português", "Português"},
            {"Español", "Español"},
            {"Català", "Català"},
            {"", ""},
            {"SpaceMarine has been added.", "Воин добалвен"},
            {"SpaceMarine already exists.", "Воин уже существует"},
            {"Element is bigger than minimum.", "Элемент больше чем минимальный"},
            {"Database broke down.", "База данных сломалась"},
            {"SpaceMarine has been removed.", "Воин списан со счетов"},
            {"Uknown Id or insufficient access rights.", "Неизвестный Id или это не ваш воин"},
            {"All items have been successfully deleted.", "Все элементы удалены"},
            {"No element has been deleted.", "Никто не удален"},
            {"Marine has been successfully updated.", "Воин изменен"},
            {"Id is not correct or insufficient access rights or dublicated elements.", "Неверный Id или это не ваш воин или дублирующий воин"},
            {"Connection lost", "Соединение потеряно"},
            {"Number format is wrong", "Неверный формат"},
            {"Error to connect to server", "Ошибка подключения к серверу"},
            {"IOException", "IOException"},
            {"Data is corrupted.", "Данные повреждены"},
            {"Please, wait", "Please, wait"}
    };

    @Override
    protected Object[][] getContents() {
        return CONTENTS;
    }
}
